# Windows Agent Test Runner
# This script properly configures and runs the Windows agent

Write-Host "=== Windows Automation Agent - Test Runner ===" -ForegroundColor Cyan
Write-Host ""

# Configuration
$CONTROL_PLANE_URL = "http://localhost:8081"
$CENTRIFUGO_URL = "ws://localhost:8000/connection/websocket"
$TENANT_ID = "test-tenant"
$PROJECT_ID = "test-project"
$AGENT_ID = "agent-windows-01"
# Use a generic test token - in production this would be generated by control plane
$JWT_TOKEN = "test-windows-token"
$LOG_LEVEL = "info"

# Set working directory
$agentDir = "C:\Users\yoges\OneDrive\Documents\My Code\Task Manager\demo\automation-agent"
Set-Location $agentDir

Write-Host "Configuration:" -ForegroundColor Green
Write-Host "  Control Plane: $CONTROL_PLANE_URL"
Write-Host "  Tenant: $TENANT_ID"
Write-Host "  Project: $PROJECT_ID"
Write-Host "  Agent ID: $AGENT_ID"
Write-Host ""

# Check binary exists
if (-not (Test-Path ".\automation-agent-windows.exe")) {
    Write-Host "ERROR: automation-agent-windows.exe not found!" -ForegroundColor Red
    exit 1
}

# Check control plane connectivity
Write-Host "Checking control plane connectivity..." -ForegroundColor Yellow
try {
    $response = Invoke-WebRequest -Uri "$CONTROL_PLANE_URL/health" -TimeoutSec 5 -ErrorAction Stop
    Write-Host "  Control Plane is accessible!" -ForegroundColor Green
} catch {
    Write-Host "  WARNING: Cannot reach control plane" -ForegroundColor Red
    Write-Host "  Make sure Docker services are running in WSL" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Starting Windows Agent..." -ForegroundColor Cyan
Write-Host "Agent will run in foreground. Press Ctrl+C to stop." -ForegroundColor Yellow
Write-Host ""

# Set environment and run
$env:CONTROL_PLANE_URL = $CONTROL_PLANE_URL
$env:CENTRIFUGO_URL = $CENTRIFUGO_URL
$env:TENANT_ID = $TENANT_ID
$env:PROJECT_ID = $PROJECT_ID
$env:AGENT_ID = $AGENT_ID
$env:JWT_TOKEN = $JWT_TOKEN
$env:LOG_LEVEL = $LOG_LEVEL

# Run agent in foreground so we can see logs
.\automation-agent-windows.exe
